Revert "Fix applying build/soong patches"
the patch breaks msm8956

bionic/libc/arch-arm/include/machine/cpu-features.h:44:6:
error: Unknown or unsupported ARM architecture

This reverts commit c740499c63b6abb25fedbd775b42d2b7d1315b19.