Revert "Update bionic patches with commits merged into AOSP"
the patch breaks msm8956

bionic/libc/arch-arm/include/machine/cpu-features.h:44:6:
error: Unknown or unsupported ARM architecture

This reverts commit ef267fab9b062a0b4fa95e3a4dbecd51ffb8e1f4.